import { PersonCompanyModel } from '@domain/lib/base-data';
import { AttachmentModel } from '@domain/lib/document-management';
import { Pagination, SelectItem } from '@view/lib/models';
import { InvoiceReturnStateEnum } from '../enum/invoice-return-state.enum';
import { InvoiceStateEnum } from '../enum/invoice-state.enum';
import { InvoiceReturnDetailModel } from './invoice-return-detail.model';
import { PurchaseInvoiceItemModel } from './purchase-invoice-item.model';

export interface InvoiceReturnModel extends Pagination {
  id?: number;
  autoGeneratedCode?: string;
  purchaseInvoice?: SelectItem;
  purchaseInvoiceAutoGeneratedCode?: string;
  purchaseInvoiceItems?: SelectItem<PurchaseInvoiceItemModel>[];
  description?: string;
  seller?: PersonCompanyModel;
  invoiceNumber?: string;
  date?: Date;
  datePersian?: string;
  fromDate?: Date;
  toDate?: Date;
  state?: InvoiceReturnStateEnum;
  invoiceStateString?: string;
  invoiceDetail?: InvoiceReturnDetailModel;
  fiscalYearId?: number;
  finalAmount?: number;
  nextState?: InvoiceStateEnum;
  attachedFiles?: AttachmentModel[];
}

export type InvoiceReturnModelFilter = keyof InvoiceReturnModel;
