import { Pagination, SelectItem } from "@view/lib/models";
import { AttachmentModel } from '../../document-management';
import { UserModel } from '../../user-management';
import { OrderStateEnum } from "../enum/order-state.enum";
import { OrderTypeEnum } from '../enum/order-type.enum';
import { SupplyMethodEnum } from '../enum/supply-method.enum';
import { OrderItemModel } from "./order-item.model";

export interface OrderModel extends Pagination {
  id?: number
  orderingOrganizationId?: number;
  orderingOrganizationLabel?: string;
  agent?: UserModel;
  state?: OrderStateEnum;
  stateString?: string;
  nextState?: OrderStateEnum;
  autoGeneratedCode?: number;
  date?: Date;
  datePersian?: string;
  fromDate?: Date;
  toDate?: Date;
  orderType?: OrderTypeEnum;
  supplyMethod?: SupplyMethodEnum;
  description?: string;
  orderItems?: OrderItemModel[];
  orderSelectItems?: SelectItem<OrderItemModel>[];
  fiscalYearId?: number;
  attachedFiles?: AttachmentModel[];
}

export type OrderModelFilter = keyof OrderModel;
