import { AttachmentModel } from "@domain/lib/document-management";
import { Pagination } from "@view/lib/models";
import { OrderModel } from "./order.model";
import { PriceEstimateItemModel } from "./price-estimate-item.model";

export interface PriceEstimateModel extends Pagination {
  autoGeneratedCode?: number;
  order?: OrderModel;
  date?: Date;
  fiscalYearId?: number;
  priceEstimateItems?: PriceEstimateItemModel[];
  attachedFiles?: AttachmentModel[];
}

export type PriceEstimateModelFilter = keyof PriceEstimateModel;
