import { Pagination, SelectItem } from '@view/lib/models';
import { PurchaseMethodEnum } from '../enum/purchase-method.enum';
import { PurchaseScaleEnum } from '../enum/purchase-scale.enum';
import { PurchaseStepTypeEnum } from '../enum/purchase-step-type.enum';
import { PurchaseStepsStateEnum } from '../enum/purchase-steps-state.enum';
import { PurchaseStepsItemModel } from './purchase-steps-item.model';

export interface PurchaseStepsModel extends Pagination {
  id?: number;
  order?: SelectItem;
  fiscalYearId?: number;
  autoGeneratedCode?: number;
  date?: Date;
  datePersian?: string;
  purchaseStepNumber?: number;
  purchaseStepType?: PurchaseStepTypeEnum;
  purchaseScale?: PurchaseScaleEnum;
  purchaseMethod?: PurchaseMethodEnum;
  state?: PurchaseStepsStateEnum;
  description?: string;
  nextState?: PurchaseStepsStateEnum;
  fromDate?: Date;
  toDate?: Date;
  purchaseStepsItems?: PurchaseStepsItemModel[];
}

export type PurchaseStepsModelFilter = keyof PurchaseStepsModel;
