export enum FiscalYearStatusEnum {
  ACTIVE = 'ACTIVE',
  COUNTING = 'COUNTING',
  INACTIVITY = 'INACTIVITY',
  FINANCIAL_PERIOD_END = 'FINANCIAL_PERIOD_END',
  INVENTORY_PERIOD_END = 'INVENTORY_PERIOD_END'
}
