
export enum TransferAndReceiptStateEnum {
  AUTOMATED_INITIAL_SUBMIT = 'AUTOMATED_INITIAL_SUBMIT',
  WAITING_FOR_CURRENCY_CONVERSION = 'WAITING_FOR_CURRENCY_CONVERSION',
  WAITING_FOR_DOCUMENT_ISSUANCE = 'WAITING_FOR_DOCUMENT_ISSUANCE',
  CANCELED = 'CANCELED',
}
