
export enum WarehousingStateEnum {
  INITIAL_SUBMIT = 'INITIAL_SUBMIT',
  COUNTING_STARTED = 'COUNTING_STARTED',
  FIRST_ROUND = 'FIRST_ROUND',
  SECOND_ROUND = 'SECOND_ROUND',
  END_OF_COUNTING = 'END_OF_COUNTING',
  MODIFIED_DOCUMENT_ISSUED = 'MODIFIED_DOCUMENT_ISSUED',
  DOCUMENT_ISSUED = 'DOCUMENT_ISSUED',
}
