import { Pagination } from "@view/lib/models";
import { WarehousingStateEnum } from '../enum/warehousing-state.enum';
import { AttachmentModel } from '../../document-management';


export interface WarehousingModel extends Pagination {
  id?: number;
  autoGeneratedCode?: number;
  state?: WarehousingStateEnum;
  stateString?: string;
  nextState?: WarehousingStateEnum;
  startDate?: Date;
  startDatePersian?: string;
  endDate?: Date;
  endDatePersian?: string;
  stockroomId?: number;
  stockroomTitle?: string;
  fiscalYearId?: number;
  fiscalYearTitle?: string;
  description?: string;
  attachedFiles?: AttachmentModel[];
}

export type WarehousingModelFilter = keyof WarehousingModel;
