import { HttpContext, HttpParams } from '@angular/common/http';
import { Component, effect, Inject, inject, untracked } from '@angular/core';
import { FormGroup, FormGroupDirective } from '@angular/forms';
import { AttachmentModel } from '@domain/lib/document-management';
import { INVOICE_RETURN_TYPE, InvoiceReturnModel, invoiceReturnTypeOptions, InvoiceStateEnum, PURCHASE_INVOICE_TYPE, PurchaseInvoiceModel, purchaseInvoiceTypeOptions } from '@domain/lib/purchase-and-orders';
import { SKIP_LOADING } from '@sadad/component-lib/src/interceptors';
import { ClDatePickerComponent } from '@sadad/component-lib/src/lib/date-picker';
import { ClFileUploadComponent } from '@sadad/component-lib/src/lib/file-uploader';
import { ClKeyFilterDirective } from '@sadad/component-lib/src/lib/key-filter';
import { ClAction, ClConfirmation, ClSelectItem } from '@sadad/component-lib/src/models';
import { AttachmentFacade, InvoiceReturnFacade } from '@state/lib/facade';
import { BaseComponent, HeadingComponent } from '@view/lib/components';
import { CommonModules, CONFIRMATION_SERVICE_CONFIG } from '@view/lib/values';
import { InvoiceReturnForm } from '../../../forms/invoice-return.form';

@Component({
  selector: 'purchase-invoice-return-initial-step',
  standalone: true,
  imports: [CommonModules, ClDatePickerComponent, HeadingComponent, ClFileUploadComponent, ClKeyFilterDirective],
  providers: [
    { provide: INVOICE_RETURN_TYPE, useValue: invoiceReturnTypeOptions },
    { provide: PURCHASE_INVOICE_TYPE, useValue: purchaseInvoiceTypeOptions },
  ],
  templateUrl: './invoice-return-initial-step.component.html',
  styles: `
  .order-attachments cl-file-uploader .cl-file-uploader-buttonbar cl-button:nth-of-type(2) { display: none }`,
})
export class InvoiceReturnInitialStepComponent extends BaseComponent<InvoiceReturnModel> {


  readonly invoiceReturnFacade = inject(InvoiceReturnFacade);
  readonly #parentFormGroup = inject(FormGroupDirective);
  readonly invoiceReturnTypeOptions = inject<ClSelectItem[]>(PURCHASE_INVOICE_TYPE);
  readonly attachmentFacade = inject(AttachmentFacade);

  httpContext = new HttpContext().set(SKIP_LOADING, true);
  purchaseInvoiceDropDown: ClSelectItem[] = [];
  deletingAttachmentId!: string;
  constructor(@Inject(CONFIRMATION_SERVICE_CONFIG) public confirmationConfig: ClConfirmation) {
    super();
    this.invoiceReturnFacade.updatePurchaseInvoiceList(InvoiceStateEnum.INITIAL_SUBMIT_INVOICE);
    this.formGroup = this.#parentFormGroup.control.get("initialStep") as FormGroup<InvoiceReturnForm>;

    effect(() => {
      const editMode = this.invoiceReturnFacade.invoiceReturnStore.state$().editMode$();
      const invoice = this.invoiceReturnFacade.invoiceReturnStore.state$().selectedInvoiceReturn$();
      untracked(() => {
        if (editMode && invoice) {
          const purchaseInvoice = this.invoiceReturnFacade.invoiceReturnStore.state$().PurchaseInvoiceList$();
          const selectedInvoice = purchaseInvoice.find(item => {
            return item.value?.id === invoice.purchaseInvoice?.value?.id
          });
          this.invoiceReturnFacade.updatePurchaseInvoiceItemList(selectedInvoice?.value?.purchaseInvoiceItems || []);
        }
      })
    })
  }

  setPurchaseInvoice(purchaseInvoice: PurchaseInvoiceModel) {
    this.formGroup.controls['purchaseInvoiceAutoGeneratedCode']?.setValue(purchaseInvoice.autoGeneratedCode);
    this.invoiceReturnFacade.updatePurchaseInvoiceItemList(purchaseInvoice.invoiceSelectItems || []);
  }

  deleteAttachment(event: { action: ClAction, row: AttachmentModel }) {
    this.deletingAttachmentId = event.row.id ?? '';
    if (event.action.key == 'download') {
      this.attachmentFacade.downloadFileById(event.row);
    }
  }

  deleteFileHttpParams() {
    return new HttpParams().set('attachmentId', this.deletingAttachmentId);
  }

  setSellerLabel(event: any) {
    this.formGroup.get('sellerLabel')?.setValue(event['title'] || event['name']);
  }
}
