import { Component, effect, inject, Input, output, untracked } from '@angular/core';
import { FormArray, FormControl, FormGroup, Validators } from '@angular/forms';
import { InvoiceReturnModel, invoiceReturnStateDataMapper, InvoiceReturnStateEnum } from '@domain/lib/purchase-and-orders';
import { ClStepsComponent } from '@sadad/component-lib/src/lib/steps';
import { ClStepItem } from '@sadad/component-lib/src/models';
import { InvoiceReturnFacade } from '@state/lib/facade';
import { BaseComponent } from '@view/lib/components';
import { CommonModules } from '@view/lib/values';
import { invoiceReturnDetailForm } from '../../forms/invoice-return-detail.form';
import { InvoiceReturnForm } from '../../forms/invoice-return.form';
import { InvoiceReturnInitialStepComponent } from "./invoice-return-initial-step/invoice-return-initial-step.component";
import { InvoiceReturnSecondStepComponent } from "./invoice-return-second-step/invoice-return-second-step.component";
import { InvoiceReturnThirdStepComponent } from "./invoice-return-third-step/invoice-return-third-step.component";

@Component({
  selector: 'purchase-add-edit-invoice-return',
  standalone: true,
  imports: [
    CommonModules,
    ClStepsComponent,
    InvoiceReturnThirdStepComponent,
    InvoiceReturnInitialStepComponent,
    InvoiceReturnSecondStepComponent
  ],
  templateUrl: './add-edit-invoice-return.component.html',
})
export class AddEditInvoiceReturnComponent extends BaseComponent<InvoiceReturnModel> {


  readonly invoiceReturnFacade = inject(InvoiceReturnFacade);

  @Input() activeIndex = 0;
  steps!: ClStepItem[];
  stepChange = output<number>();

  constructor() {
    super();
    this.initializeForm();
    this.setupDialogEffect();
    this.setupFormEffect();
    this.initializeSteps();
  }

  private initializeForm(): void {
    this.formGroup = new FormGroup({
      initialStep: new FormGroup<InvoiceReturnForm>({
        id: new FormControl,
        purchaseInvoice: new FormControl(null, { nonNullable: true }),
        autoGeneratedCode: new FormControl({ value: null, disabled: true }),
        state: new FormControl({ value: InvoiceReturnStateEnum.INITIAL_SUBMIT_INVOICE_RETURN, disabled: true }, { nonNullable: true }),
        invoiceStateString: new FormControl({ value: this.translateInvoiceState(InvoiceReturnStateEnum.INITIAL_SUBMIT_INVOICE_RETURN), disabled: true }, { nonNullable: true }),
        invoiceNumber: new FormControl('', [Validators.required]),
        date: new FormControl(new Date(), { nonNullable: true }),
        description: new FormControl,
        attachedFiles: new FormControl
      }),
      invoiceDetail: new FormGroup<invoiceReturnDetailForm>({
        additionsAmount: new FormControl(null),
        deductionsAmount: new FormControl(null),
        finalAmount: new FormControl({ value: null, disabled: true }),
        invoiceItemList: new FormArray<FormGroup>([])
      }),
    });
  }

  translateInvoiceState(state: InvoiceReturnStateEnum): string {
    return invoiceReturnStateDataMapper.get(state) as string
  }

  private setupDialogEffect(): void {
    effect(() => {
      const dismissed = this.invoiceReturnFacade.invoiceReturnStore.state$().dialogVisible$();
      untracked(() => {
        if (!dismissed) {
          this.invoiceReturnFacade.invoiceReturnStore.updateSelectedInvoiceReturn({});
          this.invoiceReturnFacade.invoiceReturnStore.updateEditMode(false);
          this.resetForm();
        }
      })
    })
  }

  private setupFormEffect(): void {
    effect(() => {
      const editMode = this.invoiceReturnFacade.invoiceReturnStore.state$().editMode$();
      const selectedInvoice = this.invoiceReturnFacade.invoiceReturnStore.state$().selectedInvoiceReturn$();
      untracked(() => {
        if (editMode) {
          this.formGroup.get('initialStep')?.patchValue(selectedInvoice);
        }
      });
    });
  }

  private initializeSteps(): void {
    this.steps = [
      {
        label: this.translate.instant('purchase-and-orders.invoice.saveDelivery'),
        status: false,
      },
      {
        label: this.translate.instant('purchase-and-orders.invoice.save-goods-service'),
        status: false,
      },
      {
        label: this.translate.instant('view-and-send'),
        status: false,
      },
    ];
  }

  resetForm() {
    this.formGroup.reset();
    this.formGroup.markAsUntouched();
    this.formGroup.markAsPristine();
  }


  nextStep(): void {
    this.formGroup.markAllAsTouched();
    const isFormValid = this.isCurrentStepValid();

    if (isFormValid) {
      this.steps[this.activeIndex].status = true;
    }
  }

  private isCurrentStepValid(): boolean {
    switch (this.activeIndex) {
      case 0:
        return this.isInitialStepValid();
      case 1:
        return this.isInvoiceDetailStepValid();
      default:
        return false;
    }
  }

  private isInitialStepValid(): boolean {
    const initialStepFormGroup = this.formGroup.get('initialStep');
    const isValid = initialStepFormGroup?.valid || false;

    if (isValid) {
      const updatedInvoice: InvoiceReturnModel = {
        ...this.formGroup.get("initialStep")?.getRawValue(),
        invoiceDetail: this.invoiceReturnFacade.invoiceReturnStore.state$().selectedInvoiceReturn$().invoiceDetail
      };
      this.invoiceReturnFacade.invoiceReturnStore.updateSelectedInvoiceReturn(updatedInvoice);
    }

    return isValid;
  }


  private isInvoiceDetailStepValid(): boolean {
    const hasInvoiceItems = !!this.invoiceReturnFacade.invoiceReturnStore.state$().selectedInvoiceReturn$()
      ?.invoiceDetail?.invoiceItemList?.
      filter((item) => !item.isDeleted)?.length;
    return hasInvoiceItems;
  }

  confirm(): void {
    const invoice = this.invoiceReturnFacade.invoiceReturnStore.state$().selectedInvoiceReturn$();
    const isEditMode = this.invoiceReturnFacade.invoiceReturnStore.state$().editMode$();

    if (isEditMode) {
      this.invoiceReturnFacade.updatedInvoiceReturn(invoice);
    } else {
      this.invoiceReturnFacade.savedInvoiceReturn(invoice);
    }

    this.resetForm();
    this.closeDialog();
  }

  closeDialog(): void {
    this.invoiceReturnFacade.toggleDialogVisibility(false);
  }

}
