
export enum GoodsDeliveryStateEnum {
  INITIAL_SUBMIT = 'INITIAL_SUBMIT',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  SENT_FROM_SOURCE = 'SENT_FROM_SOURCE',
  RECEIVED_AT_DESTINATION = 'RECEIVED_AT_DESTINATION',
  CANCELED = 'CANCELED'
}
