export enum GoodsDeliveryTypeEnum {
  PURCHASE_AND_DELIVERY_TO_ORGANIZATION = 'PURCHASE_AND_DELIVERY_TO_ORGANIZATION',
  RETURN_PURCHASE_OF_ORGANIZATION = 'RETURN_PURCHASE_OF_ORGANIZATION',
  PURCHASE_AND_DELIVERY_TO_INVENTORY = 'PURCHASE_AND_DELIVERY_TO_INVENTORY',
  RETURN_PURCHASE_OF_INVENTORY = 'RETURN_PURCHASE_OF_INVENTORY',
  DELIVERY_FROM_INVENTORY_TO_ORGANIZATION = 'DELIVERY_FROM_INVENTORY_TO_ORGANIZATION',
  RETURN_FROM_ORGANIZATION_TO_INVENTORY = 'RETURN_FROM_ORGANIZATION_TO_INVENTORY',
  TRANSFER_FROM_INVENTORY_TO_INVENTORY = 'TRANSFER_FROM_INVENTORY_TO_INVENTORY'
}
