export enum GoodsDeliveryBaseDocumentTypeEnum {
  PURCHASE_INVOICE = 'PURCHASE_INVOICE',
  PURCHASE_RETURN_INVOICE = 'PURCHASE_RETURN_INVOICE',
  GOODS_ORDER = 'GOODS_ORDER',
  GOODS_DELIVERY = 'GOODS_DELIVERY',
}
