export enum InvoiceStateEnum {
  INITIAL_SUBMIT_INVOICE = 'INITIAL_SUBMIT_INVOICE',
  WAIT_FOR_DELIVERY_INVOICE = 'WAIT_FOR_DELIVERY_INVOICE',
  WAIT_FOR_PAYMENT = 'WAIT_FOR_PAYMENT',
  PAID = 'PAID',
  CANCEL_INVOICE = 'CANCEL_INVOICE',
}
