export enum InvoiceReturnStateEnum {
  INITIAL_SUBMIT_INVOICE_RETURN = 'INITIAL_SUBMIT_INVOICE_RETURN',
  WAIT_FOR_DELIVERY_INVOICE_RETURN = 'WAIT_FOR_DELIVERY_INVOICE_RETURN',
  WAIT_FOR_PAYMENT_RETURN = 'WAIT_FOR_PAYMENT_RETURN',
  PAID_RETURN = 'PAID_RETURN',
  CANCEL_INVOICE_RETURN = 'CANCEL_INVOICE_RETURN',
}
