export enum OrderStateEnum {
  INITIAL_SUBMIT = 'INITIAL_SUBMIT',
  WAIT_FOR_DELIVERY = 'WAIT_FOR_DELIVERY',
  WAIT_FOR_FEE_ESTIMATION = 'WAIT_FOR_FEE_ESTIMATION',
  WAIT_FOR_BUDGET_ACCEPTANCE = 'WAIT_FOR_BUDGET_ACCEPTANCE',
  WAIT_FOR_BUY = 'WAIT_FOR_BUY',
  FINISH_ORDER = 'FINISH_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
}
