import { OrderModel } from '@domain/lib/purchase-and-orders';
import { OrderDto } from '../../dto';
import { Mapper } from '../../misc';
import { OrderItemMapper } from './order-item.mapper';

export class OrderSelectItemMapper implements Mapper<OrderDto, OrderModel> {
  mapFrom(param: OrderModel): OrderDto {
    return {
      id: param.id,
      documentNumber: param.autoGeneratedCode,
    };
  }

  mapTo(param: OrderDto): OrderModel {
    return {
      id: param.id,
      autoGeneratedCode: param.documentNumber,
      orderSelectItems: param.orderItems?.map(each => ({ value: new OrderItemMapper().mapTo(each), label: `${each.goodsService?.title} - ${each.goodsService?.code}` })),
    };
  }
}
