import { PurchaseInvoiceModel } from '@domain/lib/purchase-and-orders';
import { PurchaseInvoiceDto } from '../../dto';
import { Mapper } from '../../misc';
import { OrderItemMapper } from './order-item.mapper';

export class PurchaseInvoiceSelectItemMapper implements Mapper<PurchaseInvoiceModel, PurchaseInvoiceDto> {
  mapFrom(param: PurchaseInvoiceModel): PurchaseInvoiceDto {
    return {
      id: param.id,
      documentNumber: param.autoGeneratedCode,
    };
  }

  mapTo(param: PurchaseInvoiceDto): PurchaseInvoiceModel {
    return {
      id: param.id,
      autoGeneratedCode: param.documentNumber,
      invoiceSelectItems: param.invoiceItems?.map(each => ({ value: new OrderItemMapper().mapTo(each), label: `${each.goodsService?.title} - ${each.goodsService?.code}` })),
    };
  }
}
