import { PurchaseInvoiceDto } from '@api/lib/dto';
import { PurchaseInvoiceModel, purchaseInvoiceStateDataMapper } from '@domain/lib/purchase-and-orders';
import { formatDate } from '@sadad/component-lib/src/lib/date-picker';
import { Mapper } from '../../misc';
import { AttachmentMapper } from './attachment.mapper';
import { OrderItemMapper } from './order-item.mapper';
import { OrderMapper } from './order.mapper';
import { PersonCompanyMapper } from './person-company.mapper';
import { PurchaseInvoiceItemMapper } from './purchase-invoice-item.mapper';

export class PurchaseInvoiceMapper implements Mapper<PurchaseInvoiceModel, PurchaseInvoiceDto> {
  mapFrom(param: PurchaseInvoiceModel): PurchaseInvoiceDto {
    return {
      id: param.id,
      documentNumber: param.autoGeneratedCode,
      invoiceNumber: param.invoiceNumber,
      issueDate: param.date,
      stage: param.state,
      issueDateStart: param.fromDate,
      issueDateEnd: param.toDate,
      //@ts-ignore
      order: param.orderAutoGeneratedCode ? { documentNumber: param.orderAutoGeneratedCode } : new OrderMapper().mapFrom(param.order?.value || param.order || {}),
      sellerPersonCompany: { id: param.seller?.id, title: param.seller?.name },
      fiscalPeriod: {
        id: param.fiscalYearId,
      },
      deductionsAmount: param.invoiceDetail?.deductionsAmount || 0,
      additionsAmount: param.invoiceDetail?.additionsAmount || 0,
      finalAmount: param.invoiceDetail?.finalAmount || 0,
      invoiceItems: param.invoiceDetail?.invoiceItemList
        ? param.invoiceDetail.invoiceItemList.map((item) =>
          new PurchaseInvoiceItemMapper().mapFrom(item)
        ) : undefined,
      description: param.description,
      invoiceDocuments: param.attachedFiles?.map(each => new AttachmentMapper().mapFrom(each))
    };
  }
  mapTo(param: PurchaseInvoiceDto): PurchaseInvoiceModel {
    return {
      id: param.id,
      autoGeneratedCode: param.documentNumber,
      invoiceNumber: param.invoiceNumber,
      description: param.description,
      date: new Date(param.issueDate || new Date()),
      fromDate: param.issueDateStart,
      toDate: param.issueDateEnd,
      datePersian: param.issueDate
        ? formatDate(param.issueDate, 'YYYY/MM/DD')
        : '',
      state: param.stage,
      invoiceStateString: param.stage && purchaseInvoiceStateDataMapper.has(param.stage) ? purchaseInvoiceStateDataMapper.get(param.stage) : '',
      order: { label: String(param.order?.documentNumber), value: new OrderMapper().mapTo(param.order || {}) },
      orderItems: param.order?.orderItems?.map(item => ({ label: String(item.goodsService?.title), value: new OrderItemMapper().mapTo(item || {}) })),
      seller: param.sellerPersonCompany ? new PersonCompanyMapper().mapTo(param.sellerPersonCompany) : undefined,
      invoiceDetail: {
        deductionsAmount: param.deductionsAmount,
        additionsAmount: param.additionsAmount,
        finalAmount: param.finalAmount,
        finalAmountGrouped: param.finalAmount?.toString() ? param.finalAmount?.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") : '',
        invoiceItemList: param.invoiceItems
          ? param.invoiceItems.map((item) =>
            new PurchaseInvoiceItemMapper().mapTo(item)
          )
          : undefined,
      },
      totalElements: param.totalElements,
      fiscalYearId: param.fiscalPeriod?.id,
      attachedFiles: param.invoiceDocuments?.map(each => new AttachmentMapper().mapTo(each))
    };
  }
}
